### ISSUE TITLE
Remove dependendency on Node.js

### ISSUE THREAD

**Issue by photopea** [bbc/unicode-bidirectional#18]
Whould it be possible to remove the Node.js - specific code? I think such library can be made with simple strings, arrays, numbers, there is no need to have I/O etc. inside it.  I would like to use a similar tool in the browser environment.

You use many third-party libraries. I am sure that writing your own functions could improve the performance. These libraries are often stupid-proof (e.g. every time they check, if the input parameter is a string, or a number, or undefined ....) which ruins the performance.

**Comment by jameslawson** [comment]
This library is designed for use in a browser environment. The only Javascript that targets a Node.js environment should be code for running tests (code inside `/test`/ directory). Can you please be more specific about which lines of code are causing errors in a browser environment?

More work is needed for performance. There is an open issue #12 where you can contribute.

**Comment by photopea** [comment]
There is this code like `import includes from 'lodash.includes';`

I just googled, that "import" is not a command for Node.js, but it is a new specification of JS. But it is not supported by browsers yet, so I will probably see an error in my browser.

**Comment by jameslawson** [comment]
@photopea The example I provided assumed the use of a *transpiler* like [babel](https://babeljs.io/) together with a *module bundler* like [webpack](https://webpack.js.org/). These are modern buid tools used to convert (compile) ES6 to ES5 so that the code works in older browsers. Sorry, there was not much explanation about this.

I've now updated the README and given examples of how to get started.    
You have four options:
1. ES6 with import – requires a transpiler + bundler (e.g. babel, webpack)
2. CommonJs – requires a bundler (e.g. webpack)
3. RequireJs – works straight away in browser - no build tools needed
4. `<script>` tag – works straight away in browser - no build tools needed

All of the above four options can be used to get unicode-bidirectional to work in a browser environment.

**Comment by photopea** [comment]
Thank you very much. I don't use any additional software for JS development. Can you add the JS file, that works in a browser, to your repository?

**Comment by jameslawson** [comment]
You can find the JS file that works in a browser (`unicode.bidirectional.js`) here: https://github.com/bbc/unicode-bidirectional/releases

Here is an example of how to use it:
https://github.com/bbc/unicode-bidirectional/blob/master/example/example4.html
You'll need to modify the value of the `src` attribute of the `<script>` tag to point the url where you have put `unicode.bidirectional.js` on your server.

I think that should sort your problem so I'm closing this issue.

**Comment by photopea** [comment]
Ok, thanks, it works very well.
