### ISSUE TITLE
The approach to mirroring

### ISSUE THREAD

**Issue by photopea** [bbc/unicode-bidirectional#22]
I am using your library to find embedding levels and find the reordering permuation for Unicode strings. Then, I need to render the string using the available TTF / OTF file.

When a character run has an odd embedding level (goes from right to left), some characters in it must be mirrored (brackets, >, <, ...). I can do it on a geometry level, but I must know, which characters should be mirrored.

The information about mirroring is [here](http://www.unicode.org/reports/tr41/tr41-21.html#Data9). I expect, that a similar database is already built into this library. Can it be exposed to users somehow?

Another approach could be, if this library replaced actual characters in a string with a mirrored version of the character, but such "dual" character does not always exist.

What is the correct way to do it?

**Comment by jameslawson** [comment]
I've actually written some code for doing this mirroring here in [mirror.js](https://github.com/bbc/unicode-bidirectional/blob/02cd49a500a145476d9913a1f65be997154256d6/src/resolve/mirror.js)! But, I forgot to call this function and (weirdly) Unicode's test data doesn't catch this problem. It's probably a good idea to change the library so that it calls this function and replaces characters with their dual. This will fix your problem and is the recommended approach in my opinion.

I also think it's a great idea to expose this in the public API. There are two things in the library:
1. the mirroring [Map](https://github.com/mathiasbynens/unicode-9.0.0/blob/master/Bidi_Mirroring_Glyph/index.js), `mirrorMap` (this is a hard coded map generated by Mathias Bynens)
2. the mirroring function, `mirror(codepoints, levels)`, that actually performs the replacement.

I think exposing *both* of these things would be very useful. 

Please if you can, make a pull request and I'll be happy to review and merge it in. Otherwise, I'm afraid you'll have to wait for when I have time. I can *probably* (but not definitely) get this feature released this month. This project is actually a 10% time project of mine, so I don't get much time to work on it.

**Comment by photopea** [comment]
I solved it by including the list of characters, that need to be mirrored, into my code. So when a character occurs in that list, I mirror it geometrically (without any remapping).
The list is actually quite short :) I parsed it out of the official Unicode files.
    "()<>[]{}«»༺༻༼༽᚛᚜‹›⁅⁆⁽⁾₍₎∈∉∊∋∌∍∕∼∽≃≒≓≔≕≤≥≦≧≨≩≪≫≮≯≰≱≲≳≴≵≶≷≸≹≺≻≼≽≾≿⊀⊁⊂⊃⊄⊅⊆⊇⊈⊉⊊⊋⊏⊐⊑⊒⊘⊢⊣⊦⊨⊩⊫⊰⊱⊲⊳⊴⊵⊶⊷⋉⋊⋋⋌⋍⋐⋑⋖⋗⋘⋙⋚⋛⋜⋝⋞⋟⋠⋡⋢⋣⋤⋥⋦⋧⋨⋩⋪⋫⋬⋭⋰⋱⋲⋳⋴⋶⋷⋺⋻⋼⋽⋾⌈⌉⌊⌋〈〉❨❩❪❫❬❭❮❯❰❱❲❳❴❵⟃⟄⟅⟆⟈⟉⟋⟍⟕⟖⟝⟞⟢⟣⟤⟥⟦⟧⟨⟩⟪⟫⟬⟭⟮⟯⦃⦄⦅⦆⦇⦈⦉⦊⦋⦌⦍⦎⦏⦐⦑⦒⦓⦔⦕⦖⦗⦘⦸⧀⧁⧄⧅⧏⧐⧑⧒⧔⧕⧘⧙⧚⧛⧵⧸⧹⧼⧽⨫⨬⨭⨮⨴⨵⨼⨽⩤⩥⩹⩺⩽⩾⩿⪀⪁⪂⪃⪄⪋⪌⪑⪒⪓⪔⪕⪖⪗⪘⪙⪚⪛⪜⪡⪢⪦⪧⪨⪩⪪⪫⪬⪭⪯⪰⪳⪴⪻⪼⪽⪾⪿⫀⫁⫂⫃⫄⫅⫆⫍⫎⫏⫐⫑⫒⫓⫔⫕⫖⫞⫣⫤⫥⫬⫭⫷⫸⫹⫺⸂⸃⸄⸅⸉⸊⸌⸍⸜⸝⸠⸡⸢⸣⸤⸥⸦⸧⸨⸩〈〉《》「」『』【】〔〕〖〗〘〙〚〛﹙﹚﹛﹜﹝﹞﹤﹥（）＜＞［］｛｝｟｠｢｣";
